# Copyright 2023 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Authors:
# - Thomas Benz <tbenz@iis.ee.ethz.ch>

PYTHON ?= python3
LATEXMK ?= latexmk


# Shell
SHELL := /bin/bash

# Directories
RVOP_ROOT ?= .
RVOP_UTIL := $(RVOP_ROOT)/util
RVOP_OPC  := $(RVOP_ROOT)/opcodes

# Tools
RVOP_AS := $(RVOP_UTIL)/assemble_opcodes.py
RVOP_AZ := $(RVOP_UTIL)/analyze_opcodes.py
RVOP_PS := $(RVOP_UTIL)/parse_opcodes

RVOP_ASOP := $(PYTHON) $(RVOP_AS) --op_dir $(RVOP_OPC)

# Configuration
RVOP_CVA6    ?= RV64CGZicsr_Zifencei --pseudo --system
RVOP_SNITCH  ?= RV32ADFIMQZicsr_Zifencei_Xdma_Xfrep_Xssr
RVOP_MEMPOOL ?= RV32ADFIMQZicsr_Zifencei_Zfh_Xdma_Xfrep_Xssr_Xpulppostmod_Xpulpimg_Xsflt

RVOP_CV ?= RV32IMADFZicsr_Xcvmem_Xcvhwlp_Xcvbitmanip_Xcvalu_Xcvbi_Xcvmac_Xcvsimd_Xcvelw
# Ensure half-built targets are purged
.DELETE_ON_ERROR:

# Secondary Expansion
.SECONDEXPANSION:

# Output files
encoding_%.h: $(RVOP_PS) $(RVOP_AS) $(RVOP_UTIL)/encoding.h $(RVOP_ROOT)/rvop.mk
	echo "/*" > $@
	echo " * This file is auto-generated by running 'make $@' in 'riscv-opcodes'" >> $@
	echo " */" >> $@
	echo >> $@
	cat $(RVOP_UTIL)/encoding.h >> $@
	$(RVOP_PS) -c $$($(RVOP_ASOP) --system $(RVOP_$*)) >> $@

inst_%.sverilog: $(RVOP_PS) $(RVOP_AS) $(RVOP_ROOT)/rvop.mk
	$(RVOP_PS) -sverilog $$($(RVOP_ASOP) --system $(RVOP_$*)) > $@

# Analysis
clash_table_%.tex: $(RVOP_AS) $(RVOP_AZ) $(RVOP_ROOT)/rvop.mk
	$(PYTHON) $(RVOP_AZ) --report clash_matrix --exp_clashes -1 --exp_wrong_insts -1 $$($(RVOP_ASOP) --system $(RVOP_$*)) > $@

inst_table_%.tex: $(RVOP_AS) $(RVOP_AZ) $(RVOP_ROOT)/rvop.mk
	$(PYTHON) $(RVOP_AZ) --report inst_table --exp_clashes -1 --exp_wrong_insts -1 $$($(RVOP_ASOP) --system $(RVOP_$*)) > $@

free_table_%.tex: $(RVOP_AS) $(RVOP_AZ) $(RVOP_ROOT)/rvop.mk
	$(PYTHON) $(RVOP_AZ) --report free_table --exp_clashes -1 --exp_wrong_insts -1 $$($(RVOP_ASOP) --system $(RVOP_$*)) > $@

# PDFs
clash_table_%.pdf: clash_table_%.tex
	$(LATEXMK) --pdf $<
	$(LATEXMK) -c

inst_table_%.pdf: inst_table_%.tex
	$(LATEXMK) --pdf $<
	$(LATEXMK) -c

free_table_%.pdf: free_table_%.tex
	$(LATEXMK) --pdf $<
	$(LATEXMK) -c
